# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: goAdventure

before:
  hooks:
    - ./make_dungeon.sh
    - go mod tidy
  
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]


changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - name: goAdventure

    # Binaries to install
    binaries:
      - goAdventure

    # Repository to push the cask to
    repository:
      owner: andrewsjg
      name: tap
      # Optionally use a deploy token instead of GITHUB_TOKEN
      # token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    # Folder inside the repository to put the cask
    directory: Casks

    # Git author for commits
    commit_author:
      name: goreleaserbot
      email: bot@jgandrews.com

    # Caveats for the user
    caveats: |
      Colossal Cave Adventure - the classic text adventure game!

      Run with: goAdventure
      Run with AI player: goAdventure -ai

    # Your app's homepage
    homepage: "https://github.com/andrewsjg/goAdventure"

    # Your app's description
    description: "A Go implementation of the classic Colossal Cave Adventure text adventure game"

    # Skip upload if this is a pre-release
    skip_upload: auto

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
